logging:
  level:
    root: info
    org:
      springframework:
        boot:
          security: info
      hibernate:
        SQL: info
        type:
          descriptor:
            sql:
              BasicBinder: info