server:
  port: 8080

app:
  jwt:
    expire: 3600000
    secret: secret
  authorizedRedirectUris: http://localhost:3000/oauth2/callback
  apiUrl: http://localhost:8080
  front-ui: http://localhost:3000
spring-hibernate-query-utils:
  n-plus-one-queries-detection:
    error-level: error

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  servlet:
    multipart:
      enabled: true
      file-size-threshold: '1KB'
      max-file-size: '10MB'
      max-request-size: '10MB'

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ycdi8mzpijz5P6UFgoA33DpEpsEUBPJj
    url: jdbc:postgresql://dpg-clgn9fef27hc739lneeg-a.singapore-postgres.render.com/demo_52ri_4keg_8tq3
    driver-class-name: org.postgresql.Driver
  mail:
    username: danghieu14th@gmail.com
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

cors:
  allowedOrigins: "*"

vnp:
  vnp_IpAddr: ${VNP_IP_ADDRESS}
  vnp_PayUrl: ${VNP_PAY_URL}
  vnp_Returnurl: ${VNP_RETURN_URL}
  vnp_TmnCode: ${VNP_TMN_CODE}
  vnp_HashSecret: ${VNP_HASH_SECRET}
  vnp_apiUrl: ${VNP_API_URL}
  orderType: ${VNP_ORDER_TYPE}
  vnp_Command: ${VNP_COMMAND}
  vnp_Version: ${VNP_VERSION}
