server:
  port: 8080
#logging:
#  level:
#    root: info
#    org.springframework.boot.security: trace
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT}
    defer-datasource-initialization: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
  mail:
    username: ${MAIL_UESRNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

cors:
  allowedOrigins: "*"

app:
  jwt:
    expire: 3600
    secret: secret
  authorizedRedirectUris: http://localhost:3000